// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8hPWnP-nenvmhuP0IG7a_LcoBRzFLkS0',
    appId: '1:750135621005:web:3bcd7df2c70d84a40ef9c4',
    messagingSenderId: '750135621005',
    projectId: 'my-test-auth-3b2be',
    authDomain: 'my-test-auth-3b2be.firebaseapp.com',
    storageBucket: 'my-test-auth-3b2be.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDey9cyNvBBMVpeVQWgZChZDJPxbecapW8',
    appId: '1:750135621005:android:2760c19bd4687ffd0ef9c4',
    messagingSenderId: '750135621005',
    projectId: 'my-test-auth-3b2be',
    storageBucket: 'my-test-auth-3b2be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyActlvjCL4OP1oAei4Ti0wWwSwPAVtMOuE',
    appId: '1:750135621005:ios:91fa7df0f4c885970ef9c4',
    messagingSenderId: '750135621005',
    projectId: 'my-test-auth-3b2be',
    storageBucket: 'my-test-auth-3b2be.appspot.com',
    iosBundleId: 'com.example.testAndoridFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyActlvjCL4OP1oAei4Ti0wWwSwPAVtMOuE',
    appId: '1:750135621005:ios:91fa7df0f4c885970ef9c4',
    messagingSenderId: '750135621005',
    projectId: 'my-test-auth-3b2be',
    storageBucket: 'my-test-auth-3b2be.appspot.com',
    iosBundleId: 'com.example.testAndoridFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8hPWnP-nenvmhuP0IG7a_LcoBRzFLkS0',
    appId: '1:750135621005:web:a28b05b73a809ac10ef9c4',
    messagingSenderId: '750135621005',
    projectId: 'my-test-auth-3b2be',
    authDomain: 'my-test-auth-3b2be.firebaseapp.com',
    storageBucket: 'my-test-auth-3b2be.appspot.com',
  );

}